{
 "title": "Microscope Monitorization System",
 "description": "Monitor Microscope temperature, magnetic field and aceleration",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "microscope",
    "query": "SHOW TAG VALUES FROM probeTmp WITH KEY = \"microscope\""
   }
  ]
 },
 "panels": [
  {
   "title": "Magnetic field diff (nT)",
   "type": "graph",
   "description": "Each sec the magnetic field is measured. Within a minute the maximum difference is stored and displayed together with the stdev",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Mag. Field (diff, nT)" }
   ],
   "targets": [
    {
     "alias": "difference",
     "measurement": "probeMag",
     "select": [
      [
       { "params": [ "diff" ], "type": "field" },
       { "params": [ "diff" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "microscope", "operator": "=~", "value": "/^$microscope$/" }
     ]
    },
    {
     "alias": "stdev",
     "measurement": "probeMag",
     "select": [
      [
       { "params": [ "std" ], "type": "field" },
       { "params": [ "std" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "microscope", "operator": "=~", "value": "/^$microscope$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature (C)",
   "type": "graph",
   "description": "Temperature with error = 0.5 C",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Temperatire (C)" }
   ],
   "targets": [
    {
     "measurement": "probeTmp",
     "query": "SELECT \"01\" FROM \"autogen\".\"probeTmp\" WHERE (\"microscope\" =~ /^$microscope$/) AND $timeFilter AND (\"01\" > 10)",
     "select": [
      [
       { "params": [ "01" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "microscope", "operator": "=~", "value": "/^$microscope$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Magnetic Field Module (nT)",
   "type": "graph",
   "description": "Module of the TOTAL magnetic field",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Mag. Field Module (nT)" }
   ],
   "targets": [
    {
     "measurement": "probeMag",
     "query": "SELECT \"min\" FROM \"probeMag\" WHERE (\"microscope\" =~ /^$microscope$/) AND $timeFilter AND (\"min\" > 30000)",
     "select": [
      [
       { "params": [ "min" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "microscope", "operator": "=~", "value": "/^$microscope$/" }
     ]
    }
   ]
  },
  {
   "title": "Aceleration FFT",
   "type": "natel-plotly-panel",
   "description": "Log of the absolute magnitud of the FFT of the vibration sensor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "measurement": "probeVibraFFT",
     "query": "SELECT \"01\" FROM \"probeTmp\" WHERE (\"microscope\" = 'cryoArm') AND $timeFilter",
     "select": [
      [
       { "params": [ "freqs" ], "type": "field" }
      ],
      [
       { "params": [ "log_abs_fft" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "microscope", "operator": "=~", "value": "/^$microscope$/" }
     ]
    }
   ]
  },
  {
   "title": "Acceleration (G)",
   "type": "graph",
   "description": "Microscope acceleration in G. Each minute, the probe is accessed for a period of 1 second. 125-250 samples are taken and the maximum is plotted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "max (g)" }
   ],
   "targets": [
    {
     "measurement": "probeVibra",
     "query": "SELECT \"max\" FROM \"autogen\".\"probeVibra\" WHERE (\"microscope\" = 'Talos') AND $timeFilter",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ],
      [
       { "params": [ "std" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "microscope", "operator": "=~", "value": "/^$microscope$/" }
     ]
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Set title Font size",
   "type": "text",
   "gridPos": { "h": 1, "w": 5, "x": 18, "y": 14 },
   "content": "\n<style>\n.panel-title-container {\n    font-size: large;\n}\n</style>\n<!--------\n xx-small\n x-small\n small\n large\n x-large\n xx-large\n-->\n<br>\n<br>\nFile magFieldEachSecFast.py can sample up to 240 times \nper second the magnetic field.\n\n"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } }
 ]
}